### ISSUE TITLE
Support for resize

### ISSUE THREAD

**Issue by ChristianKienle** [ghaiklor/terminal-canvas#51]
This is more of a question than an issue:

I am using terminal canvas for a small cli app. I want to support the user resizing the terminal. I am catching the resize event from the underlying stream to get the new width/height. However I haven’t found an API that allows me to resize the canvas. Atm I am recreating the whole canvas (with new(...)) using the new size. However this is causing a lot of flickering.

Is there anything I am overlooking?

I think it should be possible to support resizing the window in an efficient manner... can you confirm that there is no API? Then I could work on this feature if you don’t want to do it yourself.

Btw: thank you so much for this cool project.

**Comment by ghaiklor** [comment]
@ChristianKienle wow, sorry for such a long reply :)
I just got time to get through all the notifications.

Regard your question, no. There is no such a way to change canvas size without creating a new one.

**Comment by ChristianKienle** [comment]
> Regard your question, no. There is no such a way to change canvas size without creating a new one.

Thanks for the response :)

It is a while back when I last worked on the project using terminal-canvas. I believe I ended up by disabling (showing the current size w/h instead) UI updates while the resizing occurs. This was good enough for a CLI UI. I wonder how ncurses is doing it though. :D

**Comment by ghaiklor** [comment]
If you ask me, I'd try to implement it via vectors in `terminal-canvas`, not just arrays.

The problem here, why it can't be easily done here is that, I'm pre-allocating required space for frame buffer by calling `Array.new(witdth * height)`. It is done for performance optimizations.

So, if you want to change width or height, you will be forced to allocate new array and re-assign it to variable, which is obviously will be slow. Especially, if you do it in each resize event.
